### PR TITLE
fix some minor packaging issues

### PR DESCRIPTION
**Pull request by fossfreedom**
some minor packaging issues and other fix-ups in this PR

From my POV - the greeter icon support for budgie-desktop is added for all users who use this greeter together with the budgie-desktop.

### CODE REVIEW

**Comment by clefebvre** [comment]
Please don't set debian/source/format to quilt-mode.

Other than that, everything looks good.

**Comment by fossfreedom** [comment]
sure - can do that.  Moving back to native though gives a lintian warning "debian-watch-file-in-native-package"

So I should kill the watch file if you want "native".   Should I do this?

**Comment by clefebvre** [comment]
Hi,

Yes, you can remove it.

**Comment by fossfreedom** [comment]
k - done.  thanks.

**Pull request merged**
